from __future__ import annotations

import json
import re
from pathlib import Path


def _slug(value: str) -> str:
    cleaned = re.sub(r"[^a-z0-9._-]+", "-", value.strip().lower())
    return cleaned.strip("-") or "chip"


def _package_name(chip_name: str) -> str:
    return _slug(chip_name).replace(".", "_").replace("-", "_")


def _class_label(domain: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", domain) if part) or "Domain"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _manifest(chip_name: str, domain: str, package_name: str) -> str:
    payload = {
        "schema_version": "spark-chip.v1",
        "io_protocol": "spark-hook-io.v1",
        "chip_name": chip_name,
        "domain": domain,
        "version": "0.1.0",
        "description": f"{domain} domain chip scaffold generated by spark-researcher.",
        "capabilities": ["evaluate", "suggest", "packets", "watchtower"],
        "commands": {
            "evaluate": ["python", "-m", f"{package_name}.cli", "evaluate"],
            "suggest": ["python", "-m", f"{package_name}.cli", "suggest"],
            "packets": ["python", "-m", f"{package_name}.cli", "packets"],
            "watchtower": ["python", "-m", f"{package_name}.cli", "watchtower"],
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def _project_config(chip_name: str, package_name: str, metric_name: str, goal: str) -> str:
    payload = {
        "project_name": chip_name,
        "project_root": ".",
        "eval_metric": metric_name,
        "eval_goal": goal,
        "commands": {
            "research": {
                "args": [],
                "cwd": ".",
                "kind": "chip-evaluate",
                "log_name": f"{_slug(chip_name)}.log",
            }
        },
        "metrics": {
            metric_name: {"pattern": rf"^{metric_name}:\s+([0-9.]+)$", "kind": "float"},
            "verdict_confidence": {"pattern": r"^verdict_confidence:\s+([0-9.]+)$", "kind": "float"},
        },
        "mutable_parameters": [],
        "candidate_trials": [
            {
                "candidate_id": "global-baseline",
                "candidate_summary": "Measure the generic baseline with no focused domain mechanism.",
                "hypothesis": "The baseline defines the floor before domain-specific refinements.",
                "mutations": {},
            }
        ],
        "trainers": [],
        "mutable_targets": [f"src/{package_name}", "README.md", "spark-chip.json", "pyproject.toml"],
        "chip": {"path": ".", "manifest": "spark-chip.json"},
        "memory": {"backend": "local"},
        "self_edit": {
            "command": [],
            "mutable_targets": [f"src/{package_name}", "README.md", "spark-chip.json", "pyproject.toml"],
            "prompt_preamble": "Keep the chip small, deterministic, and domain-specific.",
            "git_mode": "manual",
            "auto_push": False,
            "branch_prefix": "self-edit/",
            "main_branch": "main",
            "commit_message_template": "Apply self-edit proposal {proposal_id}",
        },
        "guardrails": {
            "max_loop_iterations": 8,
            "consecutive_discard_limit": 3,
            "require_clean_git_for_self_edit": True,
            "require_human_approval_for_self_edit": True,
            "blocked_command_fragments": ["shutdown", "format", "reg delete", "Remove-Item", "del /f", "rm -rf"],
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def _pyproject(chip_name: str) -> str:
    return "\n".join(
        [
            "[build-system]",
            'requires = ["setuptools>=68"]',
            'build-backend = "setuptools.build_meta"',
            "",
            "[project]",
            f'name = "{chip_name}"',
            'version = "0.1.0"',
            f'description = "Portable domain chip scaffold for {chip_name}."',
            'readme = "README.md"',
            'requires-python = ">=3.10"',
            "dependencies = []",
            "",
            "[tool.setuptools]",
            'package-dir = {"" = "src"}',
            "",
            "[tool.setuptools.packages.find]",
            'where = ["src"]',
        ]
    )


def _readme(chip_name: str, domain: str) -> str:
    return "\n".join(
        [
            f"# {chip_name}",
            "",
            f"`{chip_name}` is a Spark domain chip scaffold for `{domain}`.",
            "",
            "## What To Change",
            "",
            "- replace the deterministic placeholder logic in `src/.../cli.py` with real domain logic",
            "- add real candidate trials to `spark-researcher.project.json`",
            "- keep the manifest on `spark-chip.v1`",
            "- validate with `python -m spark_researcher.cli chips validate`",
            "",
            "## Quick Start",
            "",
            "```powershell",
            f"cd {chip_name}",
            "python -m pip install -e .",
            "python -m spark_researcher.cli chips status",
            "python -m spark_researcher.cli chips validate",
            "python -m spark_researcher.cli autoloop --command research",
            "```",
        ]
    )


def _gitignore() -> str:
    return "\n".join(
        [
            "artifacts/",
            "obsidian-vault/",
            "docs/beliefs/",
            "__pycache__/",
            "*.pyc",
            "*.egg-info/",
        ]
    )


def _init_file() -> str:
    return '\n'.join(['__all__ = ["__version__"]', "", '__version__ = "0.1.0"'])


def _cli_file(package_name: str, domain: str, metric_name: str, goal: str) -> str:
    label = _class_label(domain)
    better_word = "higher" if goal == "maximize" else "lower"
    baseline_value = "0.40" if goal == "maximize" else "0.60"
    improved_value = "0.62" if goal == "maximize" else "0.38"
    verdict_word = "supports" if goal == "maximize" else "supports"
    return "\n".join(
        [
            "from __future__ import annotations",
            "",
            "import argparse",
            "import json",
            "from pathlib import Path",
            "",
            "",
            "def _load(path: str) -> dict:",
            '    return json.loads(Path(path).read_text(encoding="utf-8-sig"))',
            "",
            "",
            "def _write(path: str, payload: dict) -> None:",
            '    Path(path).write_text(json.dumps(payload, indent=2, sort_keys=True) + "\\n", encoding="utf-8")',
            "",
            "",
            "def _candidate(payload: dict) -> dict[str, str]:",
            '    candidate = payload.get("candidate", {})',
            '    mutations = candidate.get("mutations", {}) if isinstance(candidate, dict) else {}',
            "    return {str(key): str(value) for key, value in mutations.items()}",
            "",
            "",
            "def evaluate(payload: dict) -> dict:",
            "    mutations = _candidate(payload)",
            f'    focused = bool(mutations.get("{domain}_axis")) or bool(mutations)',
            f"    metric_value = {improved_value} if focused else {baseline_value}",
            '    verdict_confidence = 0.84 if focused else 0.50',
            "    stdout = \"\\n\".join(",
            "        [",
            f'            "{metric_name}: " + str(metric_value),',
            '            "verdict_confidence: " + str(verdict_confidence),',
            f'            "summary: " + ("Focused {domain} candidate" if focused else "Global baseline"),',
            "        ]",
            "    )",
            "    return {",
            '        "returncode": 0,',
            '        "stdout": stdout,',
            '        "stderr": "",',
            f'        "metrics": {{"{metric_name}": metric_value, "verdict_confidence": verdict_confidence}},',
            '        "result": {',
            f'            "claim": "Focused {domain} candidates should yield {better_word} {metric_name}.",',
            f'            "verdict": "{verdict_word}" if focused else "inconclusive",',
            f'            "mechanism": "{label} mechanism placeholder.",',
            '        },',
            "    }",
            "",
            "",
            "def suggest(payload: dict) -> dict:",
            "    rows = payload.get(\"ledger_rows\", [])",
            "    limit = max(1, int(payload.get(\"limit\", 3) or 3))",
            "    tested = set()",
            "    for row in rows if isinstance(rows, list) else []:",
            "        if str(row.get(\"command_name\", \"\")) != str(payload.get(\"command_name\", \"research\")):",
            "            continue",
            "        axis = \"\"",
            "        for item in row.get(\"applied_mutations\", []) if isinstance(row.get(\"applied_mutations\"), list) else []:",
            f'            if str(item.get("name")) == "{domain}_axis":',
            '                axis = str(item.get("value", ""))',
            "        tested.add(axis)",
            "    suggestions = []",
            "    if \"primary\" not in tested:",
            "        suggestions.append(",
            "            {",
            '                "candidate_id": "primary-axis",',
            f'                "candidate_summary": "Probe the primary {domain} axis.",',
            f'                "hypothesis": "A focused {domain} axis should beat the baseline.",',
            f'                "mutations": {{"{domain}_axis": "primary"}},',
            "            }",
            "        )",
            "    return {",
            '        "baseline_metric": None,',
            f'        "reasons": ["Probe the primary {domain} axis first."][:limit],',
            '        "suggestions": suggestions[:limit],',
            "    }",
            "",
            "",
            "def packets(payload: dict) -> dict:",
            "    return {",
            '        "documents": [',
            "            {",
            f'                "kind": "{domain}_belief",',
            f'                "slug": "{domain}-placeholder",',
            f'                "title": "{label} Belief Placeholder",',
            f'                "content": "# {label} Belief Placeholder\\n\\nReplace this with real {domain} packet logic.",',
            "            }",
            "        ]",
            "    }",
            "",
            "",
            "def watchtower(payload: dict) -> dict:",
            "    return {",
            '        "pages": [',
            "            {",
            f'                "path": "07-Domains/{label}/Home.md",',
            f'                "content": "# {label} Domain\\n\\nReplace this with real watchtower pages.",',
            "            }",
            "        ]",
            "    }",
            "",
            "",
            "def main() -> None:",
            f'    parser = argparse.ArgumentParser(prog="{package_name}")',
            '    parser.add_argument("hook", choices=["evaluate", "suggest", "packets", "watchtower"])',
            '    parser.add_argument("--input", required=True)',
            '    parser.add_argument("--output", required=True)',
            "    args = parser.parse_args()",
            "    payload = _load(args.input)",
            '    if args.hook == "evaluate":',
            "        response = evaluate(payload)",
            '    elif args.hook == "suggest":',
            "        response = suggest(payload)",
            '    elif args.hook == "packets":',
            "        response = packets(payload)",
            "    else:",
            "        response = watchtower(payload)",
            "    _write(args.output, response)",
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
        ]
    )


def init_chip(
    target_dir: Path,
    *,
    chip_name: str,
    domain: str,
    metric_name: str,
    goal: str = "maximize",
    package_name: str | None = None,
) -> dict[str, str]:
    root = target_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    package = package_name or _package_name(chip_name)
    files = {
        root / ".gitignore": _gitignore(),
        root / "pyproject.toml": _pyproject(chip_name),
        root / "spark-chip.json": _manifest(chip_name, domain, package),
        root / "spark-researcher.project.json": _project_config(chip_name, package, metric_name, goal),
        root / "README.md": _readme(chip_name, domain),
        root / "src" / package / "__init__.py": _init_file(),
        root / "src" / package / "cli.py": _cli_file(package, domain, metric_name, goal),
    }
    existing = [str(path) for path in files if path.exists()]
    if existing:
        raise FileExistsError(f"Chip starter refused to overwrite existing files: {', '.join(existing)}")
    for path, content in files.items():
        _write(path, content)
    return {
        "chip_root": str(root),
        "chip_name": chip_name,
        "domain": domain,
        "metric_name": metric_name,
        "eval_goal": goal,
        "package_name": package,
        "manifest_path": str(root / "spark-chip.json"),
        "config_path": str(root / "spark-researcher.project.json"),
    }
